// Generated by ResEdit 1.4.4.19
// Copyright (C) 2006-2008
// http://www.resedit.net

HINSTANCE hInst = GetModuleHandle(0);
WNDCLASSEX wcex;
ZeroMemory(&wcex, sizeof wcex);
wcex.cbSize         = sizeof wcex;
wcex.hbrBackground  = (HBRUSH)(COLOR_3DFACE + 1);
wcex.lpszMenuName   = 0;


wcex.style          = CS_HREDRAW | CS_VREDRAW;
wcex.lpfnWndProc    = DefWindowProc;
wcex.hInstance      = hInst;
wcex.hIcon          = LoadIcon(0, (LPCTSTR)IDI_APPLICATION);
wcex.hCursor        = LoadCursor(NULL, IDC_ARROW);
wcex.lpszClassName  = WndClass55;
RegisterClassEx(&wcex);

HFONT hfont5 = CreateFont(-11, 0, 0, 0, 400, FALSE, FALSE, FALSE, 1, 400, 0, 0, 0, ("Ms Shell Dlg 2"));
HWND hwnd = CreateWindowEx(, WS_EX_STATICEDGE, ("WndClass5"), ("Pendrive Guard::Znaleziono potencjalnego wirusa!"), WS_VISIBLE | WS_BORDER | WS_CAPTION | WS_DLGFRAME | WS_POPUP | WS_SYSMENU, 0, 0, 432, 191, 0, 0, hInst, 0);
HWND hCtrl5_0 = CreateWindowEx(0, WC_BUTTON, ("Usuñ"), WS_VISIBLE | WS_CHILD | WS_TABSTOP | BS_DEFPUSHBUTTON | BS_BITMAP, 11, 125, 75, 24, hwnd, (HMENU)IDC_DELETE, hInst, 0);
SendMessage(hCtrl5_0, WM_SETFONT, (WPARAM)hfont5, FALSE);
HWND hCtrl5_1 = CreateWindowEx(0, WC_BUTTON, ("Nie podejmuj akcji"), WS_VISIBLE | WS_CHILD | WS_TABSTOP | BS_PUSHBUTTON, 86, 125, 105, 24, hwnd, (HMENU)IDC_NOACTION, hInst, 0);
SendMessage(hCtrl5_1, WM_SETFONT, (WPARAM)hfont5, FALSE);
HWND hCtrl5_2 = CreateWindowEx(WS_EX_TRANSPARENT, WC_STATIC, 0, WS_VISIBLE | WS_CHILD | WS_DISABLED | SS_BITMAP, 288, 11, 128, 128, hwnd, (HMENU)IDC_STATIC, hInst, 0);
SendMessage(hCtrl5_2, WM_SETFONT, (WPARAM)hfont5, FALSE);
HWND hCtrl5_3 = CreateWindowEx(0, WC_BUTTON, ("Dodaj wyj¹tek"), WS_VISIBLE | WS_CHILD | WS_TABSTOP | BS_PUSHBUTTON, 191, 125, 83, 23, hwnd, (HMENU)IDC_ADDEXCEPTION, hInst, 0);
SendMessage(hCtrl5_3, WM_SETFONT, (WPARAM)hfont5, FALSE);
HWND hCtrl5_4 = CreateWindowEx(WS_EX_TRANSPARENT, WC_STATIC, ("Znaleziono potencjalnego wirusa!"), WS_VISIBLE | WS_CHILD | WS_GROUP | SS_LEFT, 18, 20, 162, 20, hwnd, (HMENU)IDC_TEXT1, hInst, 0);
SendMessage(hCtrl5_4, WM_SETFONT, (WPARAM)hfont5, FALSE);
HWND hCtrl5_5 = CreateWindowEx(0, WC_STATIC, ("<<wirus>>"), WS_VISIBLE | WS_CHILD | WS_GROUP | SS_LEFT, 18, 44, 240, 49, hwnd, (HMENU)IDC_VIRUSNAME, hInst, 0);
SendMessage(hCtrl5_5, WM_SETFONT, (WPARAM)hfont5, FALSE);
HWND hCtrl5_6 = CreateWindowEx(WS_EX_TRANSPARENT, WC_STATIC, ("Co mam zrobiæ z tym ³obuzem?"), WS_VISIBLE | WS_CHILD | WS_GROUP | SS_LEFT, 18, 101, 147, 13, hwnd, (HMENU)IDC_TEXT2, hInst, 0);
SendMessage(hCtrl5_6, WM_SETFONT, (WPARAM)hfont5, FALSE);


